name: '[B-MP] EVENTS'
favicon: null
layout_spectrum: 0.3781495632138103
typography_spectrum: 0.9605288580060005
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.3790168941486627
  lightness: 0.8697633291594684
  saturation: 0.7143710076343268
  rhythmicContrast: 0.3434916927944869
purpose: []
